spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/sharebook?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/public/
  security:
    user:
      name: shakeboy
      password: shakeboy
mybatis:
  mapper-locations: classpath:com/shakeboy/mapper/*Mapping.xml
  type-aliases-package: com.shakeboy.pojo

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      shakeboy:
        mapper: debug
server:
  port: 8080
